### PR TITLE
pgremapper: Update to go 1.26.2 along with modules and fixes

### LINKED ISSUE #52: pgremapper performance limit?
Hi, I find the cluster, where `cancel-backfill` is not super fast as usual (took minutes)
1423 osds | 37920 pgs - not super big. But have 38 rack buckets with 67 hosts

What I see is that `pgremapper` use only ~ 3 cores of 24 cores CPU, and that's suspicious (low) for golang. May be this some limit in code or on compiler? Or scalability milestone for an application?

### PR DESCRIPTION
**Pull request by seanjnkns**
This PR tackles dependencies, concurrency patterns, and PG mapping logic. Key changes include upgrading Go to 1.26.2, updating dependencies across the board, and refactoring PG mapping functions to use modern Go standards (slices.Contains, improved goroutine management) for better type safety and reliability during cluster state reconciliation.

Addresses gopkg.in/yaml.v3 Denial of Service

Updates workflow to be more modern/latest (to-date)

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,2 +1,3 @@
 pgremapper
+*.cache
```
Comment (Matt1360) [inline .gitignore]: I haven't seen this before, what in the project generates a `.cache` file? I'd argue that even the vi swap files should be better left to a local `gitignore` (but that's already there).

File: backfillstate.go [hunk 2]
```diff
@@ -1,4 +1,4 @@
-// Copyright 2021 DigitalOcean
+// Copyright 2026 DigitalOcean
```
Comment (Matt1360) [inline backfillstate.go]: Copyright updates without content changes are strange, and changing the original date is incorrect. https://opensource.stackexchange.com/questions/6389/how-do-the-years-specified-in-a-copyright-statement-work and its linked wiki article has some more information about this. We should leave them alone, or, I guess we could update them to be start date to current date, but that's annoying to keep updated.

File: main.go [hunk 3]
```diff
@@ -337,7 +338,11 @@ mapping), unless --whole-pg is specified.
 					panic(err)
 				}
 
-				defer f.Close()
+				defer func() {
+					if err := f.Close(); err != nil {
+						panic(err)
```
Comment (Matt1360) [inline main.go]: This is overly verbose for closing a file; do we really need to capture and then panic if we can't close it? Close is documented to only return an error if it's already closed.

File: main.go [hunk 4]
```diff
@@ -836,7 +845,7 @@ func calcPgMappingsToUndoBackfill(excludeBackfilling, source, target bool, exclu
 								continue
 							}
 
-							if !(included(up[i]) || included(acting[i])) {
+							if !included(up[i]) && !included(acting[i]) {
```
Comment (Matt1360) [inline main.go]: ooc, what's the driver for flipping the logic here and below?

File: main.go (hunk 3 above)
Comment (seanjnkns) [reply main.go]: Yes, otherwise we get these lint errors:

`main.go:340:18: Error return value of `f.Close` is not checked (errcheck)
				defer f.Close()
				             ^
main.go:402:18: Error return value of `f.Close` is not checked (errcheck)
				defer f.Close()
				             ^
main.go:455:18: Error return value of `f.Close` is not checked (errcheck)
				defer f.Close()`

File: main.go (hunk 4 above)
Comment (seanjnkns) [reply main.go]: To address these lint errors:

`main.go:839:11: QF1001: could apply De Morgan's law (staticcheck)
							if !(included(up[i]) || included(acting[i])) {
							   ^
main.go:849:11: QF1001: could apply De Morgan's law (staticcheck)
							if !(source && included(up[i]) || target && included(acting[i])) {`

end result is the same however.

File: .gitignore (hunk 1 above)
Comment (seanjnkns) [reply .gitignore]: Yeah, I added that as I was doing a lot of building a testing.  I'll remove that here and the swap file entry and add to my own local gitignore.

File: backfillstate.go (hunk 2 above)
Comment (seanjnkns) [reply backfillstate.go]: Reverted.

File: main.go (hunk 3 above)
Comment (seanjnkns) [reply main.go]: Ended up adjusting workflow to just perform the `gofmt` checks, but with the later golangci-lint, so reverted those changes.

File: main.go (hunk 4 above)
Comment (seanjnkns) [reply main.go]: Ended up adjusting workflow to just perform the `gofmt` checks, but with the later golangci-lint, so reverted those changes.

**Review by Matt1360 — APPROVED** [review]

**Comment by k0ste** [comment]
This code will be tagged for new version? Seems have a links for #52 🤔

**Comment by k0ste** [comment]
@seanjnkns ping
